### ISSUE TITLE
Doesn't run on debain stretch

### ISSUE THREAD

**Issue by richardklose** [GitbookIO/editor-legacy#238]
The editor has a dependency on libssl1.0.0 which is replaced with libssl1.0.2 in debian stretch. The editor asks for 1.0.0 and won't use 1.0.2.

The editor crashes with a simple alert:"The git manager process has crashed. Please restart your application."
Starting it from the command line gives some more information:
```
> /opt/gitbook-editor/editor              
Gtk-Message: Failed to load module "canberra-gtk-module"
logging to /home/richard/.config/gitbook-editor/log-app.log
[2017-07-18T19:12:10.946Z] [library] info: preparing library on /home/richard/GitBook/Library
start logging to the disk
[2017-07-18T19:12:11.096Z] [uhub] info: starting uhub
[2017-07-18T19:12:11.097Z] [uhub] info: extracting uhub to /tmp/1500405131097-uhub
[2017-07-18T19:12:11.146Z] [uhub] info: uhub is extracted
[2017-07-18T19:12:11.153Z] [uhub] info: find port 44244
[2017-07-18T19:12:11.153Z] [uhub] info: spawning uhub with port 44244
[2017-07-18T19:12:11.163Z] [uhub] info: stderr: /tmp/1500405131097-uhub: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

[2017-07-18T19:12:11.164Z] [uhub] error: error with uhub process: Error: uhub exited with code 127
    at ChildProcess.r (/opt/gitbook-editor/resources/app.asar/main/index.js:29:1269)
    at ChildProcess.g (events.js:286:16)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)
[2017-07-18T19:12:17.622Z] [uhub] info: uhub exited with code 127
[2017-07-18T19:12:17.622Z] [uhub] error: error with uhub process: Error: uhub exited with code 127
    at ChildProcess.<anonymous> (/opt/gitbook-editor/resources/app.asar/main/index.js:29:1802)
    at emitTwo (events.js:111:20)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12)


```

Had to install libssl1.0.0 manually from debian jessie package sources which is not really nice.

**Comment by moozer** [comment]
I ran into exactly the same issue today.

My solution was to put libssl.so.1.0.0 and the other files from libssl1.0.0_1.0.1t-1+deb7u3_amd64.deb
into a subdirectory under /opt/gitbook, and add the directory to /etc/ld.so.conf.d/gitbook.conf.
Running 'ldconfig' then updates the list of available shared objects.

This way the old versions are available, and the system libssl.so can still be updated normally.

Still not a good solution....
